"""Added Tasks table and removed tasks column from client

Revision ID: 882a81032d79
Revises: 
Create Date: 2024-07-06 12:34:34.492328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '882a81032d79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('tasks')

    op.create_table('tasks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('assignee', sa.String(length=100), nullable=False),
        sa.Column('task', sa.String(length=255), nullable=False),
        sa.Column('status', postgresql.ENUM('not_assigned', 'in_progress', 'completed', name='statusenum'), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tasks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
